spring.application.name=Github_Updates_X_Bot
spring.threads.virtual.enabled=true

# Meta Threads API Configuration
threads.user.id=26146011638401076
threads.access.token=THAAXlZA2qGxnlBUVNTZA2EtVHZA2c2hJX3h4RnZAHX3ZAiT3NKVTluVklWejRBWm9LaWx5X2FTZAGZABOWNHWGZAPa1B0dXpMcmZA5QTJvTUR5NjR5QUxIOW9KN2daRTF0QmtmOW9NTzBOQVZAEWWhucnp4TUF6QUFZAZAm10Tk9FSlVVdnFsM1BaYnA4MVNpT2x2VTZAkMVNtZAzBSZAEowY0xFTmtidDBIdk1PNUJoQQZDZD

# Google Gemini API configuration
gemini.api.key=AIzaSyBA6IprZnMIyFChae_hBSvaoiO_UYunaNM